
name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}        
                
    - name: Install broker
      run: |
        docker pull opendxl/opendxl-broker
        docker run -d -p 8883:8883 -p 8443:8443 opendxl/opendxl-broker
        docker ps -a
              
    - name: Install dependencies
      run: |
        pip install wheel
        pip install .[test]
        python setup.py install

    - name: Provision client
      run: |
        python -m dxlclient provisionconfig sample localhost client -u admin -p password
        cat sample/dxlclient.config
        
    - name: Execute CI
      run: |
        python -m dxlmaxmindservice sample || true
        sed -i 's/licenseKey=/licenseKey=${{ secrets.MAXMIND_LICENSE_KEY }}/g' sample/dxlmaxmindservice.config
        python setup.py ci
